Repository MashdorDev/unbreaded, pull requests merged in 2024-04, with the labels that each got.

#269 Updating coreLevelTest to Gage and Safak comments
  Config/DefaultEngine.ini
  Content/Unbread/Maps/CoreLevelTest.umap
Labels: Design

#266 Fix Camera Occlusion Channel & AI death
  Content/Unbread/Core/AI/Melee/BP_MeleeAICharacter.uasset
  Content/Unbread/Core/AI/Ranged/BP_RangedAICharacter.uasset
  Source/unbread/Private/SCharacter.cpp
Labels: bug, backend

#274 Player interaction
  Content/Unbread/Environment/Hazards/LaunchPad.uasset
  Content/Unbread/Environment/Interactables/MeleeInteractables/BP_InteractTestObject.uasset
  Content/Unbread/Environment/Interactables/VentFan/BP_FanPowerButton.uasset
  Content/Unbread/Environment/Interactables/VentFan/Fan.uasset
  Content/Unbread/Maps/Testing_Maps/CharacterTestMaps/MovementTestMap.umap
  Content/Unbread/Props/BP_LabelCameraRotate.uasset
  Content/Unbread/Props/BP_LabelDash.uasset
  Content/Unbread/Props/BP_LabelHeadDetach.uasset
  Content/Unbread/Props/BP_LabelJump.uasset
  Content/Unbread/Props/BP_LabelJumpPad.uasset
  Content/Unbread/Props/BP_LabelMove.uasset
  Content/Unbread/Props/BP_LabelPunch.uasset
Labels: critical, backend, Player

#275 Core Level Test fully working
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Environment/Hazards/KillerSteamSystem.uasset
  Content/Unbread/Environment/Hazards/Swinging.uasset
  Content/Unbread/Environment/Interactables/Blender.uasset
  Content/Unbread/Environment/Interactables/Car1.uasset
  Content/Unbread/Environment/Interactables/Toaster.uasset
  Content/Unbread/Environment/Interactables/VentFan/Fan1.uasset
  Content/Unbread/Maps/CoreLevelTest.umap
  Content/Unbread/Props/BP_LabelCrumble.uasset
  Content/Unbread/Props/BP_LabelHeadDetach.uasset
  Content/Unbread/Props/BP_LabelJumpHint.uasset
Labels: Design

#288 Impact
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Core/Character/BP_ExplodingBody.uasset
  Content/Unbread/Core/Character/BP_PlayerState.uasset
  Content/Unbread/Core/GameStates/BP_GameState.uasset
  Content/Unbread/Core/Input/DefaultInputMappingContext.uasset
  Content/Unbread/Environment/Destructables/BP_DestructibleCupTest.uasset
  Content/Unbread/Environment/Destructables/BP_DestructibleObject.uasset
  Content/Unbread/Environment/Hazards/LaunchPad.uasset
  Content/Unbread/Maps/Testing_Maps/CharacterTestMaps/MovementTestMap.umap
  Content/Unbread/WeaponSystem/PunchTrigger.uasset
  Source/unbread/Private/SCharacter.cpp
  Source/unbread/Private/SInteractionComponent.cpp
  Source/unbread/Public/SCharacter.h
  Source/unbread/Public/SInteractionComponent.h
Labels: enhancement, audio, backend, Player

#293 Tweaking coreLevelTest, testing text. complete A - Z
  Content/Unbread/Environment/Cylynder.uasset
  Content/Unbread/Environment/Destructables/BasicGrayMaterial.uasset
  Content/Unbread/Environment/Destructables/ToonShader.uasset
  Content/Unbread/Environment/Interactables/VentFan/Fan.uasset
  Content/Unbread/Environment/Interactables/VentFan/Fan1.uasset
  Content/Unbread/Maps/CoreLevelTest.umap
Labels: Design

#294 Added Several Meshes
  Content/Unbread/Art/Environment_Assets/SM_Cube_Grey.uasset
  Content/Unbread/Art/Environment_Assets/SM_Floor_20x20_Planks.uasset
  Content/Unbread/Art/Environment_Assets/SM_Floor_20x20_Tiles.uasset
  Content/Unbread/Art/Environment_Assets/SM_Floor_Cap1_20x20_Planks_Floor_20x20_Planks_005.uasset
  Content/Unbread/Art/Environment_Assets/SM_Floor_Cap2_20x20_Planks_Floor_20x20_Planks_003.uasset
  Content/Unbread/Art/Environment_Assets/SM_Hanging_Light_Sphere.uasset
  Content/Unbread/Art/Environment_Assets/SM_Vent_Circle_Connector_Cylinder_006.uasset
  Content/Unbread/Art/Environment_Assets/SM_Vent_Circle_Cylinder.uasset
  Content/Unbread/Art/Environment_Assets/SM_Vent_Corner_Cube_014.uasset
  Content/Unbread/Art/Environment_Assets/SM_Vent_Straight_Cube_001.uasset
  Content/Unbread/Maps/CoreLevel.umap
Labels: graphics

#296 Graphics customization
  Content/Unbread/Core/GameModes/BP_GameInstance.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-Black.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-BlackItalic.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-BlackItalic_Font.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-Black_Font.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-Bold.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-BoldItalic.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-BoldItalic_Font.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-Bold_Font.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-ExtraBold.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-ExtraBoldItalic.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-ExtraBoldItalic_Font.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-ExtraBold_Font.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-ExtraLight.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-ExtraLightItalic.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-ExtraLightItalic_Font.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-ExtraLight_Font.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-Italic.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-Italic_Font.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-Light.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-LightItalic.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-LightItalic_Font.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-Light_Font.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-Medium.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-MediumItalic.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-MediumItalic_Font.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-Medium_Font.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-Regular.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-Regular_Font.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-SemiBold.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-SemiBoldItalic.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-SemiBoldItalic_Font.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-SemiBold_Font.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-Thin.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-ThinItalic.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-ThinItalic_Font.uasset
  Content/Unbread/Core/UI/Fonts/Montserrat-Thin_Font.uasset
  Content/Unbread/Core/UI/Widgets/WBP_Main_Menu.uasset
  Content/Unbread/Core/UI/Widgets/WBP_PauseMenu.uasset
  Source/unbread/Private/SMenuButton.cpp
  Source/unbread/Private/SNavigatableMenu.cpp
  Source/unbread/Public/SMenuButton.h
  Source/unbread/Public/SNavigatableMenu.h
Labels: enhancement-ui, graphics, Top Priority

#298 fix punch not affecting Ranged AI & fix punch animation glitch
  Content/Unbread/Art/Characters/GingerbreadMan/GBM_Throw2.uasset
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Environment/Interactables/VentFan/Fan.uasset
  Content/Unbread/Maps/CoreLevelTest.umap
  Source/unbread/Private/SInteractionComponent.cpp
Labels: bug, critical, backend, Player

#300 Light baking & Credits
  Config/DefaultEngine.ini
  Content/Unbread/Art/Environment_Assets/BP_Hanging_Light.uasset
  Content/Unbread/Art/Environment_Assets/SM_Counter_10x6.uasset
  Content/Unbread/Art/Environment_Assets/SM_Counter_6x6.uasset
  Content/Unbread/Art/Environment_Assets/SM_Counter_6x6_Corner.uasset
  Content/Unbread/Art/Environment_Assets/SM_Floor_20x20_Planks.uasset
  Content/Unbread/Art/Environment_Assets/SM_Floor_20x20_Tiles.uasset
  Content/Unbread/Art/Environment_Assets/SM_Floor_Cap1_20x20_Planks.uasset
  Content/Unbread/Art/Environment_Assets/SM_Floor_Cap1_20x20_Planks_Floor_20x20_Planks_005.uasset
  Content/Unbread/Art/Environment_Assets/SM_Floor_Cap2_20x20_Planks.uasset
  Content/Unbread/Art/Environment_Assets/SM_Floor_Cap2_20x20_Planks_Floor_20x20_Planks_003.uasset
  Content/Unbread/Art/Environment_Assets/SM_Vent_Corner.uasset
  Content/Unbread/Art/Environment_Assets/SM_Vent_Corner_Cube_014.uasset
  Content/Unbread/Art/Environment_Assets/SM_Vent_Straight.uasset
  Content/Unbread/Art/Environment_Assets/SM_Vent_Straight_Cube_001.uasset
  Content/Unbread/Art/Props/SM_Cake_Rectangle2.uasset
  Content/Unbread/Art/Props/SM_Cash_Register.uasset
  Content/Unbread/Core/UI/Widgets/WBP_Main_Menu.uasset
  Content/Unbread/Core/UI/Widgets/WBP_Main_Menu_Backup.uasset
  Content/Unbread/Core/UI/Widgets/WBP_PauseMenu.uasset
  Content/Unbread/Environment/Hazards/BP_ChoppingKnife.uasset
  Content/Unbread/Maps/CoreLevel.umap
  unbreaded.uproject
Labels: bug, graphics, backend

#310 Core level test04 - hotFIx
  Content/Unbread/Art/Materials/Custom_Depth_Draw_Material_Inst.uasset
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Environment/Hazards/LaunchPad.uasset
  Content/Unbread/Maps/CoreLevelTest.umap
Labels: bug, backend

#311 Walls dissolve
  Content/Unbread/Art/Materials/M_Dissolve.uasset
  Content/Unbread/Art/Materials/M_Dissolve_Inst.uasset
  Content/Unbread/Art/Materials/M_OutlineEmmisive.uasset
  Content/Unbread/Art/Materials/M_OutlineEmmisive_Inst.uasset
  Content/Unbread/Art/Materials/M_Shiny_MaterialEmmisive.uasset
  Content/Unbread/Art/Materials/M_Shiny_MaterialEmmisive_Inst.uasset
  Content/Unbread/Core/AI/Melee/BP_MeleeAICharacter.uasset
  Content/Unbread/Core/AI/Melee/BT_MeleeAI.uasset
  Content/Unbread/Core/AI/Ranged/BP_RangedAICharacter.uasset
  Content/Unbread/Core/AI/Ranged/BT_RangedAI.uasset
  Content/Unbread/Core/AI/Ranged/Eqs/SelectTarget.uasset
  Content/Unbread/Core/AI/Ranged/Path/Patrolling.uasset
  Content/Unbread/Core/Camera/IntroLevelSequence.uasset
  Content/Unbread/Environment/BP_ArenaWall.uasset
  Content/Unbread/Environment/Hazards/LaunchPad.uasset
  Content/Unbread/Environment/Interactables/ServerBot/BP_ServerSpline1.uasset
  Content/Unbread/Maps/CoreLevelTest.umap
  Content/Unbread/Maps/MainLevel.umap
  Content/Unbread/Maps/TurorialLevel.umap
  Content/Unbread/Projectiles/BP_PrimaryProjectile.uasset
  Source/unbread/Private/BTTask_Fire.cpp
  Source/unbread/Private/BTTask_GetRandomPoints.cpp
  Source/unbread/Private/BTTask_SetAnimationState.cpp
  Source/unbread/Private/BTTask_SmoothlyRotate.cpp
  Source/unbread/Private/SPathActor.cpp
  Source/unbread/Private/SRangedAICharacter.cpp
  Source/unbread/Public/BTTask_GetRandomPoints.h
  Source/unbread/Public/BTTask_SetAnimationState.h
  Source/unbread/Public/BTTask_SmoothlyRotate.h
  Source/unbread/Public/SPathActor.h
  Source/unbread/Public/SRangedAICharacter.h
  Source/unbread/Public/SRanged_AIController.h
  Source/unbread/Public/S_SmartObject.h
Labels: enhancement

#314 Starting area
  Content/Unbread/Art/Materials/M_Glass.uasset
  Content/Unbread/Art/Props/SM_Cash_Register.uasset
  Content/Unbread/Environment/Hazards/StoveTopTrap.uasset
  Content/Unbread/Environment/Interactables/RotatingTable.uasset
  Content/Unbread/Maps/CoreLevelTest.umap
  Content/Unbread/Maps/Testing_Maps/CharacterTestMaps/MovementTestMap.umap
  Content/Unbread/Maps/Testing_Maps/CharacterTestMaps/MovementTestMap02.umap
Labels: critical, Design

#313 Added camera folowing direction of the player, Fixed jump pads
  Content/Unbread/Art/AnimNotifes/BP_JumpNotify.uasset
  Content/Unbread/Core/AI/Melee/BP_MeleeAICharacter.uasset
  Content/Unbread/Core/AI/Ranged/BP_RangedAICharacter.uasset
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Core/GameModes/RespawnGamemode.uasset
  Content/Unbread/Environment/Hazards/LaunchPad.uasset
  Source/unbread/Private/BTTask_SelectTarget.cpp
  Source/unbread/Private/SCharacter.cpp
  Source/unbread/Private/SExplodingBody.cpp
  Source/unbread/Private/SRangedAICharacter.cpp
  Source/unbread/Public/SCharacter.h
Labels: enhancement

#319 VFX
  Content/Unbread/Art/FX/FX_BodyExplode.uasset
  Content/Unbread/Art/FX/FX_Crumble.uasset
  Content/Unbread/Art/FX/FX_Electricity.uasset
  Content/Unbread/Art/FX/Materials/M_Lighning.uasset
  Content/Unbread/Art/FX/Materials/M_Shockwave.uasset
  Content/Unbread/Art/FX/Materials/Textures/LighningMask.uasset
  Content/Unbread/Art/FX/Materials/Textures/SingleLighningMask.uasset
  Content/Unbread/Core/Character/BP_ExplodingBody.uasset
  Content/Unbread/Environment/B_Emmisive.uasset
  Content/Unbread/Environment/B_Emmisive_Inst.uasset
Labels: graphics, Design

#320 Credits menu fix
  Content/Unbread/Core/GameModes/BP_GameInstance.uasset
  Content/Unbread/Core/UI/Widgets/WBP_Main_Menu.uasset
  Content/Unbread/Core/UI/Widgets/WBP_Main_Menu_Backup.uasset
  Content/Unbread/Core/UI/Widgets/WBP_PauseMenu.uasset
  Content/Unbread/Core/UI/Widgets/WBP_PauseMenuOld.uasset
  Content/Unbread/Core/UI/Widgets/WBP_WinMenu.uasset
  Content/Unbread/Maps/CoreLevelTest.umap
  Content/Unbread/Maps/MainMenu.umap
  Source/unbread/Private/SNavigatableMenu.cpp
  Source/unbread/Private/SRespawnGameMode.cpp
  Source/unbread/Private/SRespawnGameMode.cpp~
Labels: enhancement-ui, critical

#322 adjust camera rotation speed
  Content/Unbread/Core/AI/Ranged/BP_RangedAICharacter.uasset
  Content/Unbread/Core/Character/BP_Character.uasset
Labels: Player

#324 Ragdoll hot fix
  Content/Unbread/Art/Characters/GingerbreadMan/GBM_Head.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/GingerbreadMan_PhysicsAsset1.uasset
  Content/Unbread/Core/Character/BP_Character.uasset
Labels: enhancement

#325 improved camera auto panning and ai behaviour
  Content/Movies/Attach - Made with Clipchamp.mp4
  Content/Movies/Detach - Made with Clipchamp.mp4
  Content/Movies/Long Jump - Trim.mp4
  Content/Movies/Punch - Made with Clipchamp.mp4
  Content/Movies/head Explode - Made with Clipchamp.mp4
  Content/Movies/jump - Made with Clipchamp.mp4
  Content/Unbread/Art/AnimNotifes/BP_FootstepNotify.uasset
  Content/Unbread/Art/Characters/Loaf/LoafAnimInstance.uasset
  Content/Unbread/Art/Characters/Loaf/Loaf_Attack.uasset
  Content/Unbread/Art/Characters/Loaf/Loaf_Attack_Montage.uasset
  Content/Unbread/Core/AI/Melee/BP_MeleeAICharacter.uasset
  Content/Unbread/Core/AI/Melee/BT_MeleeAI.uasset
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Core/Misc/ActiveImage.uasset
  Content/Unbread/Environment/SpawnVolume.uasset
  Content/Unbread/Maps/CoreLevelTest.umap
  Content/Unbread/Maps/VideoRecording.umap
  Content/Unbread/Media/Attach_-_Made_with_Clipchamp.uasset
  Content/Unbread/Media/Detach_-_Made_with_Clipchamp.uasset
  Content/Unbread/Media/Long_Jump_-_Made_with_Clipchamp.uasset
  Content/Unbread/Media/Long_Jump_-_Trim.uasset
  Content/Unbread/Media/Materials/Attach_Video_Mat.uasset
  Content/Unbread/Media/Materials/Detach.uasset
  Content/Unbread/Media/Materials/ExplodeJump.uasset
  Content/Unbread/Media/Materials/ExplosionJump.uasset
  Content/Unbread/Media/Materials/LongJump.uasset
  Content/Unbread/Media/Materials/Punch.uasset
  Content/Unbread/Media/Materials/RegularJump.uasset
  Content/Unbread/Media/Materials/SimpleJump.uasset
  Content/Unbread/Media/MediaPlayer.uasset
  Content/Unbread/Media/MediaPlayer_Video.uasset
  Content/Unbread/Media/MediaWidget.uasset
  Content/Unbread/Media/Punch_-_Made_with_Clipchamp.uasset
  Content/Unbread/Media/head_Explode_-_Made_with_Clipchamp.uasset
  Content/Unbread/Media/jump_-_Made_with_Clipchamp.uasset
  Content/Unbread/Projectiles/BP_PrimaryProjectile.uasset
  Source/unbread/Private/SCharacter.cpp
  Source/unbread/Public/SCharacter.h
  Source/unbread/Public/SRangedAICharacter.h
  unbreaded.uproject
Labels: enhancement

#326 added two more videos
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Core/Character/BP_ExplodingBody.uasset
  Content/Unbread/Core/GameStates/BP_GameState.uasset
  Content/Unbread/Core/Misc/ActiveImage.uasset
  Content/Unbread/Environment/BP_ArenaWall.uasset
  Content/Unbread/Maps/CoreLevelTest.umap
  Content/Unbread/Maps/VideoRecording.umap
  Content/Unbread/Media/ExplodeJump.uasset
  Content/Unbread/Media/ExplodeKill.uasset
  Content/Unbread/Media/Explode_Jump_-_Made_with_Clipchamp.uasset
  Content/Unbread/Media/Explode_Kil.uasset
  Content/Unbread/Media/MediaWidget.uasset
Labels: enhancement

#329 Tutorial fixes
  Content/Unbread/Art/Environment_Assets/NewBlueprint.uasset
  Content/Unbread/Core/Tutorials/BP_TutorialVolume.uasset
  Content/Unbread/Environment/BP_ArenaWall.uasset
  Content/Unbread/Environment/Interactables/RotatingTable.uasset
  Content/Unbread/Maps/CoreLevelTest.umap
  Content/Unbread/Media/MediaWidget.uasset
Labels: bug, backend, Design, UI

#330 Electric
  Content/Unbread/Art/AnimNotifes/BP_PunchStartAnimNotify.uasset
  Content/Unbread/Audio/UNBREADED2_Cue.uasset
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Core/Character/BP_ExplodingBody.uasset
  Content/Unbread/Environment/Hazards/ElectocutedCable/BP_CableAttachmentComp.uasset
  Content/Unbread/Environment/Hazards/ElectocutedCable/BP_CableAttachmentPoint.uasset
  Content/Unbread/Environment/Hazards/ElectocutedCable/BP_ElectrocutedCable.uasset
  Content/Unbread/Environment/Interactables/VentFan/BP_FanPowerButton.uasset
  Content/Unbread/Maps/CoreLevelTest.umap
  Content/Unbread/Maps/Testing_Maps/CharacterTestMaps/MovementTestMap02.umap
  Source/unbread/Public/S_SmartObject.h
Labels: Design

#331 fixed some stuff to working manner
  Content/Unbread/Maps/CoreLevelTest.umap
Labels: bug, critical

#332 Hot fix critic
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Environment/BP_ArenaWall.uasset
  Content/Unbread/Maps/CoreLevelTest.umap
  Content/Unbread/Projectiles/BP_PrimaryProjectile.uasset
Labels: bug, critical
