Repository MashdorDev/unbreaded, pull requests merged in 2024-03, with the labels that each got.

#144 Make the level path more clear & Make the splitting mechanic more interesting
  Content/Unbread/Art/Characters/GingerbreadMan/GBM_Body_PhysicsAsset.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/GingerbreadMan_PhysicsAsset.uasset
  Content/Unbread/Art/Environment_Assets/Display_1.uasset
  Content/Unbread/Art/Environment_Assets/SM_Sink.uasset
  Content/Unbread/Art/Props/SM_Cake1.uasset
  Content/Unbread/Art/Props/SM_Cake2.uasset
  Content/Unbread/Art/Props/SM_Cake_Rectangle2.uasset
  Content/Unbread/Core/AI/Melee/BP_MeleeAICharacter.uasset
  Content/Unbread/Core/AI/Ranged/BP_RangedAICharacter.uasset
  Content/Unbread/Core/Character/BP_ExplodingBody.uasset
  Content/Unbread/Maps/CoreLevelTest.umap
  Source/unbread/Private/AIManager.cpp
  Source/unbread/Private/SCharacter.cpp
  Source/unbread/Private/SCrumbles.cpp
  Source/unbread/Private/SExplodingBody.cpp
  Source/unbread/Private/SRespawnGameMode.cpp
  Source/unbread/Public/SCharacter.h
  Source/unbread/Public/SCrumbles.h
  Source/unbread/Public/SExplodingBody.h
Labels: enhancement, graphics, Design, Player

#147 Gas based AI
  Config/DefaultEngine.ini
  Content/Unbread/Core/AI/Ranged/BP_RangedAICharacter.uasset
  Content/Unbread/Core/AI/Ranged/BP_RangedAICharacterGAS.uasset
  Content/Unbread/Core/AI/Ranged/BP_TestAI.uasset
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Core/Character/BP_ExplodingBody.uasset
  Content/Unbread/Core/GAS/Abilities/GA_GumShooter_Fire.uasset
  Content/Unbread/Core/GameModes/RespawnGamemode.uasset
  Content/Unbread/Environment/Destructables/BP_DestructibleObject.uasset
  Content/Unbread/Maps/Testing_Maps/CharacterTestMaps/CharacterTest02.umap
  Content/Unbread/Maps/Testing_Maps/RangedAI.umap
  Content/Unbread/Maps/Testing_Maps/RangedAI_MAP02.umap
  Content/Unbread/Projectiles/BP_PrimaryProjectile.uasset
  Content/Unbread/Projectiles/BP_PrimaryProjectile1.uasset
  Content/Unbread/Projectiles/BP_ProjectileCannon.uasset
  Content/Unbread/Projectiles/BP_ProjectileCannon1.uasset
  Content/Unbread/Projectiles/BP_ProjectileCannonDonut.uasset
  Content/Unbread/Props/BP_DestructableCube.uasset
  Content/Unbread/WeaponSystem/BP_DonutBullet.uasset
  Content/Unbread/WeaponSystem/BP_GumBullet.uasset
  Content/Unbread/WeaponSystem/BP_ProjectileBase.uasset
  Source/unbread/Private/SExplodingBody.cpp
  Source/unbread/Private/SRangedAICharacter.cpp
  Source/unbread/Public/SHealthAttributeSet.h
  Source/unbread/Public/SRangedAICharacter.h
Labels: backend

#148 Redo changes to BP_character for opening thapause menu.
  Content/Unbread/Core/Character/BP_Character.uasset
Labels: enhancement-ui

#153 Pre-Alpha Fixes: Ragdoll and Spawn Volumes
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Core/Character/BP_ExplodingBody.uasset
  Content/Unbread/Environment/SpawnVolume.uasset
  Content/Unbread/Maps/CoreLevelTest.umap
Labels: bug, critical, backend

#157 fixed the nav meshes desplacement in the core level
  Content/Unbread/Maps/CoreLevelTest.umap
Labels: enhancement

#158 Fixed the SkeletalCube error
  Content/Unbread/WeaponSystem/BP_GumShooter.uasset
  Content/Unbread/WeaponSystem/BP_WeaponBase.uasset
Labels: bug, critical, Top Priority

#159 Changing perspective for core level, added level two map file
  Content/Unbread/Maps/CoreLevelTest.umap
  Content/Unbread/Maps/SecondLevelTest1.umap
Labels: Design

#167 Mesh assets
  Config/DefaultEngine.ini
  Content/Unbread/Art/Environment_Assets/SM_Counter_10x6.uasset
  Content/Unbread/Art/Environment_Assets/SM_Counter_6x6.uasset
  Content/Unbread/Art/Environment_Assets/SM_Counter_6x6_Corner.uasset
  Content/Unbread/Art/FX/FX_HeatDistortion.uasset
  Content/Unbread/Art/FX/Materials/M_Distortion.uasset
  Content/Unbread/Environment/Hazards/BP_StoveTop.uasset
  Content/Unbread/Environment/Hazards/StoveTopTrap.uasset
  Content/Unbread/Environment/Hazards/StoveTopTrap1.uasset
  Content/Unbread/Environment/Hazards/StoveTopTrap2.uasset
  Content/Unbread/Environment/Interactables/RotatingTable.uasset
  Content/Unbread/Maps/CoreLevelTest.umap
Labels: graphics, Design

#171 UI art impl
  Content/Unbread/Core/GameModes/RespawnGamemode.uasset
  Content/Unbread/Core/Input/UIInputActions/IA_UI_Escape.uasset
  Content/Unbread/Core/Input/UIInputMappingContext.uasset
  Content/Unbread/Core/UI/Widgets/WBP_Main_Menu.uasset
  Content/Unbread/Core/UI/Widgets/WBP_PauseMenu.uasset
  Content/Unbread/Core/UI/Widgets/WBP_PlayerHud.uasset
  Content/Unbread/Core/UI/Widgets/WBP_PlayerHudOld.uasset
  Source/unbread/Private/SNavigatableMenu.cpp
  Source/unbread/Private/SPlayerHealthBar.cpp
  Source/unbread/Public/SNavigatableMenu.h
  Source/unbread/Public/SPlayerHealthBar.h
Labels: enhancement-ui

#173 AoE and control update
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Core/Character/BP_ExplodingBody.uasset
  Content/Unbread/Core/GAS/Abilities/GA_FireAbility.uasset
  Content/Unbread/Core/GAS/Abilities/GA_GumShooter_Fire.uasset
  Content/Unbread/Core/GAS/Abilities/GA_ReloadWeapon.uasset
  Content/Unbread/Core/GAS/Abilities/GA_TestAbility.uasset
  Content/Unbread/Core/GameModes/BP_GameMode.uasset
  Content/Unbread/Core/GameModes/RespawnGamemode.uasset
  Content/Unbread/Core/GameStates/BP_GameState.uasset
  Content/Unbread/Core/Input/DefaultInputMappingContext.uasset
  Content/Unbread/Environment/Destructables/BP_DestructibleObject.uasset
  Content/Unbread/Maps/Testing_Maps/AOE.umap
  Content/Unbread/Maps/Testing_Maps/CharacterTestMaps/CharacterTest02.umap
  Content/Unbread/Projectiles/BP_PrimaryProjectile.uasset
  Content/Unbread/Projectiles/BP_ProjectileExplosive.uasset
  Content/Unbread/WeaponSystem/BP_DamageArea.uasset
  Source/unbread/Private/SCharacter.cpp
  Source/unbread/Private/SDestructible.cpp
  Source/unbread/Private/SPlayerState.cpp
  Source/unbread/Public/SCharacter.h
Labels: enhancement, critical, backend, controller

#182 remove debug sphere on projectile hit
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Environment/Destructables/BP_DestructibleObject.uasset
  Content/Unbread/Maps/Testing_Maps/CharacterTestMaps/CharacterTest02.umap
  Content/Unbread/Projectiles/BP_PrimaryProjectile.uasset
Labels: bug

#185 Immersive HUD implemented
  Content/Unbread/Core/UI/Widgets/NewHudTest.uasset
  Content/Unbread/Core/UI/Widgets/WBP_PlayerHealthTracker.uasset
  Content/Unbread/Core/UI/Widgets/WBP_PlayerHud.uasset
  Content/Unbread/Core/UI/Widgets/WBP_PlayerHudOld2.uasset
  Content/Unbread/Maps/Testing_Maps/AudioTest.umap
Labels: enhancement-ui

#186 Character and move set
  Config/DefaultEngine.ini
  Config/DefaultGameplayTags.ini
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Core/Character/BP_Character_backup.uasset
  Content/Unbread/Core/Character/BP_ExplodingBody.uasset
  Content/Unbread/Core/Character/BP_PlayerState.uasset
  Content/Unbread/Core/GAS/Abilities/GA_TestAbility.uasset
  Content/Unbread/Core/GAS/Effects/GE_DefaultAttributes.uasset
  Content/Unbread/Core/GAS/Effects/GE_HealUp.uasset
  Content/Unbread/Core/GAS/Effects/GE_SetHealth.uasset
  Content/Unbread/Core/GameModes/BP_GameMode.uasset
  Content/Unbread/Core/GameModes/RespawnGamemode.uasset
  Content/Unbread/Core/Interactables/BP_HealUp.uasset
  Content/Unbread/Core/UI/Widgets/NewHudTest.uasset
  Content/Unbread/Core/UI/Widgets/WBP_PlayerHealthTracker.uasset
  Content/Unbread/Environment/Destructables/BP_DestructibleObject.uasset
  Content/Unbread/Maps/Testing_Maps/CharacterTestMaps/CharacterTest02.umap
  Content/Unbread/Projectiles/BP_PrimaryProjectile.uasset
  Content/Unbread/Projectiles/BP_ProjectileCannonDonut.uasset
  Content/Unbread/WeaponSystem/BP_DonutBullet.uasset
  Content/Unbread/WeaponSystem/BP_ProjectileBase.uasset
  Source/unbread/Private/SCharacter.cpp
  Source/unbread/Private/SHealthAttributeSet.cpp
  Source/unbread/Public/SCharacter.h
Labels: enhancement, enhancement-ui, critical, backend, Player, Top Priority, controller

#192 Shadows and level adjustments
  Content/Unbread/Art/Characters/GingerbreadMan/SM_CrumblePile.uasset
  Content/Unbread/Art/Environment_Assets/SM_Sink.uasset
  Content/Unbread/Art/FX/FX_CookieExplode.uasset
  Content/Unbread/Art/FX/Materials/M_CookieParticle.uasset
  Content/Unbread/Art/FX/Materials/M_ShadowDecal.uasset
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Core/Interactables/BP_CrumblePile.uasset
  Content/Unbread/Environment/Interactables/LowPolyWater/Water1.uasset
  Content/Unbread/Maps/CoreLevelTest.umap
  Source/unbread/DynamicCameraComponent.cpp
  Source/unbread/Private/SCrumbles.cpp
  Source/unbread/Public/SCrumbles.h
Labels: enhancement, graphics, backend, Design

#211 Core level new map file.
  Content/Unbread/Art/Environment_Assets/SM_Table_10x6.uasset
  Content/Unbread/Art/Props/SM_Bun_Star.uasset
  Content/Unbread/Environment/Destructables/BP_DestructibleBread.uasset
  Content/Unbread/Environment/Destructables/BP_DestructibleBreadKnife.uasset
  Content/Unbread/Environment/Destructables/BP_DestructibleBun.uasset
  Content/Unbread/Environment/Destructables/BP_DestructibleCup.uasset
  Content/Unbread/Environment/Destructables/BP_DestructibleCup1.uasset
  Content/Unbread/Environment/Destructables/BP_DestructiblePlate.uasset
  Content/Unbread/Environment/Destructables/BP_DestructibleStarBread.uasset
  Content/Unbread/Environment/Hazards/BP_ChoppingKnife.uasset
  Content/Unbread/Environment/Hazards/BP_RotateRoll.uasset
  Content/Unbread/Environment/Hazards/BP_StoveTop.uasset
  Content/Unbread/Environment/Hazards/BeltTrap.uasset
  Content/Unbread/Environment/Hazards/BeltTrap2.uasset
  Content/Unbread/Environment/Hazards/HammerSmash.uasset
  Content/Unbread/Environment/Hazards/LaunchPad.uasset
  Content/Unbread/Environment/Hazards/SinkingObjects/BP_SinkingPlatform.uasset
  Content/Unbread/Environment/Hazards/SpinningStar.uasset
  Content/Unbread/Environment/Hazards/Swinging.uasset
  Content/Unbread/Environment/Interactables/BaguetteLimo.uasset
  Content/Unbread/Environment/Interactables/Car.uasset
  Content/Unbread/Environment/Interactables/Car1.uasset
  Content/Unbread/Environment/Interactables/Car2.uasset
  Content/Unbread/Environment/Interactables/LowPolyWater/Oil.uasset
  Content/Unbread/Environment/Interactables/RotatingCakeBase.uasset
  Content/Unbread/Environment/Interactables/SeeSaw.uasset
  Content/Unbread/Environment/Interactables/SeeSaw1.uasset
  Content/Unbread/Maps/CoreLevel.umap
  Content/Unbread/Maps/CoreLevelTest.umap
  Content/Unbread/Maps/CoreLevelTest1.umap
  Content/Unbread/Maps/SecondLevelTest1.umap
Labels: Design

#210 fixed the occlusion problem(Thanks Gage)
  Content/Unbread/Core/Character/BP_Character.uasset
  Source/unbread/Private/SCharacter.cpp
  Source/unbread/Private/SRespawnGameMode.cpp
  Source/unbread/Public/SCharacter.h
  Source/unbread/Public/SRespawnGameMode.h
Labels: enhancement

#212 Tab based menu
  Content/FMOD/Desktop/Master.bank
  Content/FMOD/Desktop/Master.strings.bank
  Content/FMOD/Events/CakeFS.uasset
  Content/FMOD/Events/KitchenObjets.uasset
  Content/FMOD/Events/MetalFS.uasset
  Content/FMOD/Events/SinkFS.uasset
  Content/FMOD/Events/Stovetop_Spark.uasset
  Content/FMOD/Events/UI.uasset
  Content/FMOD/Events/WoodFS.uasset
  Content/FMOD/PrivateIntegrationData/AssetLookup.uasset
  Content/Unbread/Core/UI/Widgets/WBP_Main_Menu.uasset
  Source/unbread/Private/SNavigatableMenu.cpp
  Source/unbread/Public/SMenuButton.h
  Source/unbread/Public/SNavigatableMenu.h
Labels: enhancement-ui, critical

#214 Added a shadow to to the player and adjusted the occlusion material
  Content/Unbread/Art/FX/Materials/M_ShadowDecal.uasset
  Content/Unbread/Art/Materials/M_Fade_Material.uasset
  Content/Unbread/Core/Character/BP_Character.uasset
Labels: graphics, Design, Player

#216 Improved movement
  Content/Unbread/Art/Characters/GingerbreadMan/GBM_Jump.uasset
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Core/GameModes/RespawnGamemode.uasset
  Content/Unbread/Core/Input/DefaultInputMappingContext.uasset
  Content/Unbread/Core/Input/InputActions/IA_Jump.uasset
  Content/Unbread/Maps/Testing_Maps/CharacterTestMaps/MovementTestMap.umap
  Source/unbread/Private/SCharacter.cpp
  Source/unbread/Public/SCharacter.h
Labels: enhancement, Player, Top Priority, controller

#219 fix launch head dynamics
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Maps/Testing_Maps/CharacterTestMaps/MovementTestMap.umap
  Source/unbread/Private/SCharacter.cpp
  Source/unbread/Public/SCharacter.h
Labels: bug, Player, Top Priority, controller

#220 add D-Pad support in controller / adjust character capsule volume
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Core/Input/DefaultInputMappingContext.uasset
  Content/Unbread/Maps/Testing_Maps/CharacterTestMaps/MovementTestMap.umap
Labels: Player, controller

#227 add Multiple Input Mapping Configurations
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Core/Input/AlternateInputMappingContext01.uasset
  Content/Unbread/Core/Input/AlternateInputMappingContext02.uasset
  Content/Unbread/Core/Input/AlternateInputMappingContext03.uasset
  Content/Unbread/Core/Input/DefaultInputMappingContext.uasset
  Content/Unbread/Core/Input/InverseRotationInputMappingContext.uasset
  Content/Unbread/Maps/Testing_Maps/CharacterTestMaps/MovementTestMap.umap
Labels: Player, Top Priority, controller

#235 Melee
  Content/Unbread/Art/Characters/GingerbreadMan/ABP_GingerbreadMan.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/GBM_Throw2.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/GingerbreadMan_Skeleton.uasset
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Core/Character/BP_ExplodingBody.uasset
  Content/Unbread/Core/GameStates/BP_GameState.uasset
  Content/Unbread/Core/Input/DefaultInputMappingContext.uasset
  Content/Unbread/Environment/Destructables/BP_DestructibleCupTest.uasset
  Content/Unbread/Environment/Destructables/BP_DestructibleObject.uasset
  Content/Unbread/Environment/Interactables/MeleeInteractables/BP_InteractTestObject.uasset
  Content/Unbread/Maps/CoreLevel.umap
  Content/Unbread/Maps/CoreLevelTest.umap
  Content/Unbread/Maps/Testing_Maps/CharacterTestMaps/MovementTestMap.umap
  Content/Unbread/WeaponSystem/BPI_Punch.uasset
  Content/Unbread/WeaponSystem/PunchTrigger.uasset
  Source/unbread/Private/SCharacter.cpp
  Source/unbread/Private/SGameplayInterface.cpp
  Source/unbread/Private/SInteractTestObject.cpp
  Source/unbread/Private/SInteractionComponent.cpp
  Source/unbread/Public/SCharacter.h
  Source/unbread/Public/SGameplayInterface.h
  Source/unbread/Public/SInteractTestObject.h
  Source/unbread/Public/SInteractionComponent.h
Labels: Player, Top Priority

#242 Pause menu new
  Content/Unbread/Core/GameModes/RespawnGamemode.uasset
  Content/Unbread/Core/UI/Widgets/WBP_Main_Menu.uasset
  Content/Unbread/Core/UI/Widgets/WBP_PauseMenu.uasset
  Content/Unbread/Core/UI/Widgets/WBP_PauseMenuOld.uasset
  Content/Unbread/Core/UI/Widgets/WBP_PlayerHud.uasset
  Content/Unbread/Core/UI/Widgets/WBP_SplashScreen.uasset
  Source/unbread/Private/SMenuButton.cpp
  Source/unbread/Private/SNavigatableMenu.cpp
  Source/unbread/Public/SMenuButton.h
  Source/unbread/Public/SNavigatableMenu.h
Labels: enhancement-ui, critical

#244 Collision fix
  Content/Unbread/Environment/BP_WinVolume.uasset
  Content/Unbread/Environment/Hazards/BP_StoveTop.uasset
  Content/Unbread/Environment/Hazards/StoveTopTrap.uasset
  Content/Unbread/Environment/SpawnVolume.uasset
Labels: bug, critical, Top Priority

#245 Level design week14 - collision fixed, level cleaned
  Content/Unbread/Environment/Interactables/BaguetteLimo.uasset
  Content/Unbread/Environment/Interactables/Car.uasset
  Content/Unbread/Environment/Interactables/Car2.uasset
  Content/Unbread/Environment/Interactables/VentFan/BP_FanPowerButton.uasset
  Content/Unbread/Environment/Interactables/VentFan/BP_Interface.uasset
  Content/Unbread/Environment/Interactables/VentFan/Fan.uasset
  Content/Unbread/Maps/CoreLevelTest.umap
Labels: Design

#250 Camera and collision
  Config/DefaultEngine.ini
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Environment/BP_WinVolume.uasset
  Content/Unbread/Environment/Hazards/BP_StoveTop.uasset
  Content/Unbread/Environment/Hazards/StoveTopTrap.uasset
  Content/Unbread/Environment/SpawnVolume.uasset
  Content/Unbread/Maps/CoreLevelTest.umap
  Content/Unbread/WeaponSystem/PunchTrigger.uasset
  Source/unbread/Private/SCharacter.cpp
  Source/unbread/Public/SCharacter.h
Labels: Player, controller

#252 Footsteps test
  Config/DefaultEngine.ini
  Content/Unbread/Art/AnimNotifes/BP_FootstepNotify.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/GBM_RunForward.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/GBM_WalkForward.uasset
  Content/Unbread/Art/Environment_Assets/SM_Counter_10x6.uasset
  Content/Unbread/Art/Environment_Assets/SM_Counter_6x6.uasset
  Content/Unbread/Art/Environment_Assets/SM_Counter_6x6_Corner.uasset
  Content/Unbread/Art/Environment_Assets/SM_Oven_10x6.uasset
  Content/Unbread/Art/Environment_Assets/SM_Table_10x6.uasset
  Content/Unbread/Art/Props/SM_Cake1.uasset
  Content/Unbread/Art/Props/SM_Cake2.uasset
  Content/Unbread/Art/Props/SM_Cake_Rectangle1.uasset
  Content/Unbread/Art/Props/SM_Cake_Rectangle2.uasset
  Content/Unbread/Art/Props/SM_Cake_Slice1.uasset
  Content/Unbread/Art/Props/SM_Cake_Slice2.uasset
  Content/Unbread/Art/Props/SM_Cash_Register.uasset
  Content/Unbread/Art/Props/SM_Cinnamon_Bun.uasset
  Content/Unbread/Art/Props/SM_Cookie1.uasset
  Content/Unbread/Art/Props/SM_Cookie2.uasset
  Content/Unbread/Art/Props/SM_Cookie_Heart.uasset
  Content/Unbread/Art/Props/SM_Cupcake_Stand.uasset
  Content/Unbread/Art/Props/SM_Dish_Dryer.uasset
  Content/Unbread/Art/Props/SM_Espresso_Machine.uasset
  Content/Unbread/Art/Props/SM_Macaroon1.uasset
  Content/Unbread/Art/Props/SM_Macaroon2.uasset
  Content/Unbread/Art/Props/SM_Macaroon3.uasset
  Content/Unbread/Art/Props/SM_Pan_Dough.uasset
  Content/Unbread/Art/Props/SM_Toaster_Oven.uasset
  Content/Unbread/Art/Props/Trolley_Dough_Pans.uasset
  Content/Unbread/Art/Props/Trolley_Small.uasset
  Content/Unbread/Environment/Hazards/SoundFloorMetal.uasset
  Content/Unbread/Environment/Hazards/SoundFloorWood.uasset
  Content/Unbread/Environment/PhysicalMaterials/PM_Cake.uasset
  Content/Unbread/Environment/PhysicalMaterials/PM_Metal.uasset
  Content/Unbread/Environment/PhysicalMaterials/PM_Wood.uasset
  Content/Unbread/Maps/Testing_Maps/AudioTest.umap
Labels: critical, audio

#253 Jump Animation Improvements
  Content/Unbread/Art/Characters/GingerbreadMan/ABP_GingerbreadMan.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/GBM_Jump_InAir.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/GBM_Jump_Landed.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/GBM_Jump_Launch.uasset
Labels: graphics, backend

#255 Attack
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Core/DynamicCamera/Release/BP_CameraRegisterLookAtTarget.uasset
  Content/Unbread/Core/GameStates/BP_GameState.uasset
  Content/Unbread/Core/Input/DefaultInputMappingContext.uasset
  Content/Unbread/Core/Input/InputActions/IA_SecondaryAttack.uasset
  Content/Unbread/Environment/Destructables/BP_DestructibleObject.uasset
  Content/Unbread/Maps/Testing_Maps/CharacterTestMaps/MovementTestMap.umap
  Content/Unbread/WeaponSystem/PunchTrigger.uasset
  Source/unbread/Private/SCharacter.cpp
  Source/unbread/Public/SCharacter.h
Labels: Player, controller

#258 fixed access violation fix
  Content/Unbread/Core/AI/Melee/BP_MeleeAICharacter.uasset
  Content/Unbread/Core/AI/Ranged/BP_RangedAICharacter.uasset
  Source/unbread/Private/SCharacter.cpp
Labels: enhancement

#259 small level adjustments, and fixed player movement while level sequen…
  Content/Unbread/Maps/CoreLevel.umap
  Source/unbread/Private/SCharacter.cpp
  Source/unbread/Public/SCharacter.h
Labels: enhancement

#263 AI now shoots properly
  Source/unbread/Private/BTTask_SmoothlyRotate.cpp
  Source/unbread/Private/SRangedAICharacter.cpp
Labels: enhancement
