Repository MashdorDev/unbreaded, pull requests merged in 2024-02, with the labels that each got.

#39 Meshes and materials
  Config/DefaultEditor.ini
  Content/Unbread/Art/Characters/Donut/Donut.uasset
  Content/Unbread/Art/Characters/Donut/Donut_PhysicsAsset.uasset
  Content/Unbread/Art/Characters/Donut/Donut_Skeleton.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/ABP_GingerbreadMan.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/BS_GingerbreadMovement_2D.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/GBM_Idle.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/GBM_RunForward.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/GBM_WalkForward.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/GingerbreadMan.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/GingerbreadMan_PhysicsAsset.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/GingerbreadMan_Skeleton.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/SK_GingerbreadMan.uasset
  Content/Unbread/Art/Characters/Loaf/Loaf.uasset
  Content/Unbread/Art/Characters/Loaf/Loaf_PhysicsAsset.uasset
  Content/Unbread/Art/Characters/Loaf/Loaf_Skeleton.uasset
  Content/Unbread/Art/Materials/M_Diffuse_Material.uasset
  Content/Unbread/Art/Materials/M_Outline.uasset
  Content/Unbread/Art/Materials/M_Shiny_Material.uasset
  Content/Unbread/Art/Materials/Textures/T_Color_Palate.uasset
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Core/Input/DefaultInputMappingContext.uasset
  Content/Unbread/Core/Input/InputActions/IA_SprintAction.uasset
  Content/Unbread/Core/Interactables/BP_ActivatableTest.uasset
  Content/Unbread/Core/Interactables/BP_LeverTest.uasset
  Content/Unbread/Maps/CharacterMeshTesting.umap
  Content/Unbread/Maps/CharacterTest01.umap
  Content/Unbread/Maps/PuzzleMechanicTesting.umap
  Source/unbread/Private/ActivationInterface.cpp
  Source/unbread/Private/Lever.cpp
  Source/unbread/Private/MovableObject.cpp
  Source/unbread/Private/MovableObjectGoal.cpp
  Source/unbread/Private/SCharacter.cpp
  Source/unbread/Public/ActivationInterface.h
  Source/unbread/Public/InteractInterface.h
  Source/unbread/Public/Lever.h
  Source/unbread/Public/MovableObject.h
  Source/unbread/Public/MovableObjectGoal.h
  Source/unbread/Public/SCharacter.h
Labels: enhancement, graphics

#41 Animations
  Content/Unbread/Art/Characters/GingerbreadMan/ABP_GingerbreadMan.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/GBM_Idle.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/GBM_Jump.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/GBM_RunForward.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/GBM_Throw.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/GBM_Throw2.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/GingerbreadMan_Skeleton.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/SK_GingerbreadMan.uasset
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Maps/CharacterMeshTesting.umap
  Content/Unbread/Projectiles/BP_PrimaryProjectile.uasset
  Source/unbread/Private/SCharacter.cpp
  Source/unbread/Private/SProjectile.cpp
  Source/unbread/Public/SCharacter.h
  Source/unbread/Public/SProjectile.h
Labels: enhancement, graphics

#46 new branch with all env hazards stuff
  Content/Unbread/Environment/Hazards/BP_ChoppingKnife.uasset
  Content/Unbread/Environment/Hazards/BP_ConveyorBelt.uasset
  Content/Unbread/Environment/Hazards/BP_FallingKnives.uasset
  Content/Unbread/Environment/Hazards/BP_ModularConveyorBelt.uasset
  Content/Unbread/Environment/Hazards/BP_SpawnKnife.uasset
  Content/Unbread/Maps/HazardsTest01.umap
  Source/unbread/Private/SSpawnableBase.cpp
  Source/unbread/Private/S_FallingKnives.cpp
  Source/unbread/Public/SSpawnableBase.h
  Source/unbread/Public/S_FallingKnives.h
Labels: Design

#47 Projectile
  Config/DefaultEngine.ini
  Config/DefaultGameplayTags.ini
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Core/Character/BP_CharacterTest.uasset
  Content/Unbread/Core/GAS/Abilities/GA_TestAbility.uasset
  Content/Unbread/Core/GAS/Effects/GE_DefaultAttributes.uasset
  Content/Unbread/Core/GAS/Effects/GE_HealUp.uasset
  Content/Unbread/Core/GAS/Effects/GE_ShieldUp.uasset
  Content/Unbread/Core/GameModes/BP_GameModeTest.uasset
  Content/Unbread/Core/Input/DefaultInputMappingContext.uasset
  Content/Unbread/Core/Input/InputActions/IA_InteractionAbility.uasset
  Content/Unbread/Core/Input/InputActions/IA_SecondaryAttack.uasset
  Content/Unbread/Core/Interactables/BP_HealUp.uasset
  Content/Unbread/Core/Interactables/BP_ShieldUp.uasset
  Content/Unbread/Maps/CharacterTest02.umap
  Content/Unbread/Projectiles/BP_PrimaryProjectile.uasset
  Content/Unbread/Projectiles/BP_PrimaryProjectile1.uasset
  Content/Unbread/Projectiles/BP_ProjectileCannon.uasset
  Content/Unbread/Projectiles/BP_ProjectileCannon1.uasset
  Content/Unbread/Projectiles/BP_ProjectileExplosive.uasset
  Content/Unbread/Props/BP_DestructableCube.uasset
  Content/Unbread/Props/BP_PhysicsCube.uasset
  Source/unbread/Private/SCharacter.cpp
  Source/unbread/Private/SProjectile.cpp
  Source/unbread/Public/SCharacter.h
  Source/unbread/Public/SProjectile.h
Labels: backend

#50 bind player attributes to HUD
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Core/GAS/Effects/GE_DefaultAttributes.uasset
  Content/Unbread/Core/UI/Widgets/WBP_PlayerHud.uasset
  Content/Unbread/Maps/CharacterTest02.umap
  Source/unbread/Private/SCharacter.cpp
  Source/unbread/Private/SPlayerHealthBar.cpp
  Source/unbread/Public/SCharacter.h
  Source/unbread/Public/SPlayerHealthBar.h
Labels: backend

#56 Pull Splitting Mechanic Prototype
  Config/DefaultEngine.ini
  Content/Unbread/Art/Environment_Assets/Oven_10x6.uasset
  Content/Unbread/Art/Materials/M_Diffuse_Material.uasset
  Content/Unbread/Art/Materials/M_Shiny_Material.uasset
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Core/DynamicCamera/Release/BP_CameraRegisterLookAtTarget.uasset
  Content/Unbread/Core/GameModes/BP_GameMode.uasset
  Content/Unbread/Environment/Hazards/BP_TestKillVolume.uasset
  Content/Unbread/Maps/BlockoutLevelTest.umap
  Content/Unbread/Maps/CharacterTest01.umap
  Source/unbread/DynamicCameraComponent.cpp
  Source/unbread/Private/SCharacter.cpp
  Source/unbread/Public/CameraRegisterVolume.cpp
  Source/unbread/Public/CameraRegisterVolume.h
  Source/unbread/Public/SCharacter.h
Labels: enhancement

#59 Player controller update
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Core/Character/BP_CharacterRotation.uasset
  Content/Unbread/Core/Input/DefaultInputMappingContext.uasset
  Content/Unbread/Core/Input/InputActions/IA_InteractionAbility.uasset
  Content/Unbread/Core/Input/InputActions/IA_Jump.uasset
  Content/Unbread/Core/Input/InputActions/IA_SecondaryAttack.uasset
  Content/Unbread/Core/Input/InputActions/IA_Temp_Projectile.uasset
  Content/Unbread/Maps/CharacterTest02.umap
  Source/unbread/Private/SCharacter.cpp
  Source/unbread/Public/SCharacter.h
Labels: backend

#60 Ranged AI
  Content/Unbread/Core/AI/Ranged/BB_RangedAI.uasset
  Content/Unbread/Core/AI/Ranged/BP_RangedAICharacter.uasset
  Content/Unbread/Core/AI/Ranged/BP_Ranged_AIController.uasset
  Content/Unbread/Core/AI/Ranged/BT.uasset
  Content/Unbread/Core/AI/Ranged/BT_RangedAI.uasset
  Content/Unbread/Core/AI/Ranged/Eqs/MoveAwayLocation.uasset
  Content/Unbread/Core/AI/Ranged/Eqs/SelectTarget.uasset
  Content/Unbread/Core/AI/Ranged/Eqs/Strafe.uasset
  Content/Unbread/Core/AI/Ranged/MyAIManager.uasset
  Content/Unbread/Core/AI/Ranged/Path/Default.uasset
  Content/Unbread/Core/AI/Ranged/Path/MySPathActor.uasset
  Content/Unbread/Core/AI/Ranged/Path/Patrolling.uasset
  Content/Unbread/Core/AI/Ranged/UI/DetectionMeter.uasset
  Content/Unbread/Core/AI/Ranged/UI/UIInterface.uasset
  Content/Unbread/Maps/RangedAI.umap
  Source/unbread/Private/AIManager.cpp
  Source/unbread/Private/BTDecorator_DistanceCheck.cpp
  Source/unbread/Private/BTTask_FindStrafeLocation.cpp
  Source/unbread/Private/BTTask_Fire.cpp
  Source/unbread/Private/BTTask_GetRandomPoints.cpp
  Source/unbread/Private/BTTask_OverrideState.cpp
  Source/unbread/Private/BTTask_SelectTarget.cpp
  Source/unbread/Private/BTTask_SetAnimationState.cpp
  Source/unbread/Private/BTTask_SetBlackboardKey.cpp
  Source/unbread/Private/EnemyQueryContext.cpp
  Source/unbread/Private/SCharacter.cpp
  Source/unbread/Private/SPathActor.cpp
  Source/unbread/Private/SRangedAICharacter.cpp
  Source/unbread/Private/SRanged_AIController.cpp
  Source/unbread/Private/S_SmartObject.cpp
  Source/unbread/Private/SameFactionTest.cpp
  Source/unbread/Public/AIManager.h
  Source/unbread/Public/BTDecorator_DistanceCheck.h
  Source/unbread/Public/BTTask_FindStrafeLocation.h
  Source/unbread/Public/BTTask_Fire.h
  Source/unbread/Public/BTTask_GetRandomPoints.h
  Source/unbread/Public/BTTask_OverrideState.h
  Source/unbread/Public/BTTask_SelectTarget.h
  Source/unbread/Public/BTTask_SetAnimationState.h
  Source/unbread/Public/BTTask_SetBlackboardKey.h
  Source/unbread/Public/CameraRegisterVolume.cpp
  Source/unbread/Public/EnemyQueryContext.h
  Source/unbread/Public/SCharacter.h
  Source/unbread/Public/SPathActor.h
  Source/unbread/Public/SRangedAICharacter.h
  Source/unbread/Public/SRanged_AIController.h
  Source/unbread/Public/S_SmartObject.h
  Source/unbread/Public/SameFactionTest.h
  Source/unbread/unbread.Build.cs
  Source/unbread/unbread.h
  unbread.uproject
Labels: enhancement

#63 Level1 core level into dev
  Content/Unbread/Environment/Hazards/BP_SinkingPlatformKitchen.uasset
  Content/Unbread/Environment/Hazards/BP_TestKillVolumeWater.uasset
  Content/Unbread/Environment/Interactables/DoorBar.uasset
  Content/Unbread/Environment/Interactables/GarbageFlip.uasset
  Content/Unbread/Environment/Interactables/RotatingLid.uasset
  Content/Unbread/Maps/CoreLevelTest.umap
  Content/Unbread/Maps/LevelTest1.umap
  Content/Unbread/Maps/LevelTest2.umap
  Content/Unbread/Maps/_GENERATED/alanm/Box_3B3D9A4B.uasset
Labels: Design

#69 adjust character controls and add impulse on character crumble
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Core/Character/BP_ExplodingBody.uasset
  Content/Unbread/Core/Input/DefaultInputMappingContext.uasset
  Content/Unbread/Core/Interactables/BP_CrumblePile.uasset
  Content/Unbread/Maps/CharacterTest02.umap
  Source/unbread/Private/SCharacter.cpp
Labels: backend

#77 This branch adds all the models made so far into the project
  Content/Unbread/Art/Environment_Assets/Oven_10x6.uasset
  Content/Unbread/Art/Environment_Assets/SM_Oven_10x6.uasset
  Content/Unbread/Art/Environment_Assets/SM_Table_10x6.uasset
  Content/Unbread/Art/Environment_Assets/SM_Table_6x6.uasset
  Content/Unbread/Art/Props/SM_Bowl.uasset
  Content/Unbread/Art/Props/SM_Coffee_Mug.uasset
  Content/Unbread/Art/Props/SM_Cupcake_Cherry.uasset
  Content/Unbread/Art/Props/SM_Cupcake_Chocolate.uasset
  Content/Unbread/Art/Props/SM_Cupcake_Heart.uasset
  Content/Unbread/Art/Props/SM_Cupcake_Stand.uasset
  Content/Unbread/Art/Props/SM_Cutting_Board.uasset
  Content/Unbread/Art/Props/SM_Dish_Dryer.uasset
  Content/Unbread/Art/Props/SM_Dispenser_Cream.uasset
  Content/Unbread/Art/Props/SM_Dispenser_Large.uasset
  Content/Unbread/Art/Props/SM_Dispenser_Pink.uasset
  Content/Unbread/Art/Props/SM_Dispenser_Whipped_Cream.uasset
  Content/Unbread/Art/Props/SM_Knife_Bread.uasset
  Content/Unbread/Art/Props/SM_Knife_Sharp.uasset
  Content/Unbread/Art/Props/SM_Pan_Dough.uasset
  Content/Unbread/Art/Props/SM_Plate_1.uasset
  Content/Unbread/Art/Props/SM_Plate_2.uasset
  Content/Unbread/Art/Props/SM_Plate_3.uasset
  Content/Unbread/Art/Props/SM_Plate_Teacup_Blue.uasset
  Content/Unbread/Art/Props/SM_Plate_Teacup_Pink.uasset
  Content/Unbread/Art/Props/SM_Plate_Teacup_White.uasset
  Content/Unbread/Art/Props/SM_Rolling_Pin.uasset
  Content/Unbread/Art/Props/Teacup.uasset
  Content/Unbread/Art/Props/Teapot.uasset
  Content/Unbread/Art/Props/Trolley_Dough_Pans.uasset
  Content/Unbread/Art/Props/Trolley_Small.uasset
  Content/Unbread/Maps/ModelTestLevel.umap
Labels: graphics

#76 Animation fixes and Spline Camera
  Content/Unbread/Art/Characters/Donut/Donut.uasset
  Content/Unbread/Art/Characters/Donut/Donut_Attack.uasset
  Content/Unbread/Art/Characters/Donut/Donut_Skeleton.uasset
  Content/Unbread/Art/Characters/Donut/Donut_Walk.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/ABP_GingerbreadMan.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/BS_GingerbreadMovement_2D.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/GBM_Strafe_L.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/GBM_Strafe_R.uasset
  Content/Unbread/Art/Characters/GingerbreadMan/GBM_WalkBackward.uasset
  Content/Unbread/Art/Characters/Loaf/Loaf.uasset
  Content/Unbread/Art/Characters/Loaf/Loaf_Attack.uasset
  Content/Unbread/Art/Characters/Loaf/Loaf_Skeleton.uasset
  Content/Unbread/Art/Characters/Loaf/Loaf_Walk.uasset
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Core/Character/BP_CharacterRotation.uasset
  Content/Unbread/Core/DynamicCamera/Release/BP_CameraRegisterLookAtTarget.uasset
  Content/Unbread/Core/DynamicCamera/Release/BP_CameraSplineVolume.uasset
  Content/Unbread/Maps/DynamicCameraTest01.umap
  Source/unbread/Private/SCharacter.cpp
  Source/unbread/Public/CameraRegisterVolume.cpp
Labels: enhancement, graphics, backend

#79 changed rotation function to smooth out mouse controls
  Content/Unbread/Maps/CharacterTest02.umap
  Source/unbread/Private/SCharacter.cpp
Labels: backend

#86 Core level detailing
  Content/Unbread/Art/Props/SM_Cupcake_Cherry.uasset
  Content/Unbread/Art/Props/SM_Cupcake_Chocolate.uasset
  Content/Unbread/Art/Props/SM_Cupcake_Heart.uasset
  Content/Unbread/Art/Props/SM_Cupcake_Stand.uasset
  Content/Unbread/Art/Props/SM_Dish_Dryer.uasset
  Content/Unbread/Environment/Hazards/BP_SinkingPlatform.uasset
  Content/Unbread/Environment/Hazards/BP_SinkingPlatformKitchen.uasset
  Content/Unbread/Environment/Hazards/BP_TestKillVolume.uasset
  Content/Unbread/Environment/Hazards/SinkingObjects/BP_SinkingPlatform.uasset
  Content/Unbread/Environment/Hazards/SinkingObjects/BP_SinkingPlatformKitchen.uasset
  Content/Unbread/Environment/Hazards/SinkingObjects/BP_SinkingPlatformKitchen2.uasset
  Content/Unbread/Environment/Hazards/SinkingObjects/BP_SinkingPlatformKitchen3.uasset
  Content/Unbread/Environment/Hazards/SinkingObjects/BP_SinkingPlatformKitchen4.uasset
  Content/Unbread/Environment/Hazards/StoveTopTrap.uasset
  Content/Unbread/Environment/Hazards/StoveTopTrap1.uasset
  Content/Unbread/Environment/Hazards/StoveTopTrap2.uasset
  Content/Unbread/Environment/Interactables/GarbageFlip.uasset
  Content/Unbread/Environment/Interactables/RotatingLid.uasset
  Content/Unbread/Environment/Interactables/RotatingTable.uasset
  Content/Unbread/Maps/CoreLevelTest.umap
  Content/Unbread/Maps/HazardsTest01.umap
  Content/Unbread/Maps/Level2Test1.umap
  Content/Unbread/Maps/_GENERATED/alanm/Box_665558DF.uasset
Labels: Design

#87 Ai fix
  Content/Unbread/Core/AI/Ranged/BP_RangedAICharacter.uasset
  Content/Unbread/Maps/RangedAI.umap
  Content/Unbread/Projectiles/BP_PrimaryProjectile.uasset
  Source/unbread/Private/SRangedAICharacter.cpp
  Source/unbread/Public/SProjectile.h
  Source/unbread/Public/SRangedAICharacter.h
Labels: enhancement

#91 integrated Range AI into the Core level
  Content/Unbread/Maps/CoreLevelTest.umap
Labels: enhancement

#92 Organized Map Folder
  Content/Unbread/Maps/AudioTest.umap
  Content/Unbread/Maps/BlockoutLevelTest.umap
  Content/Unbread/Maps/CharacterMeshTesting.umap
  Content/Unbread/Maps/CharacterTestMaps/CharacterTest02.umap
  Content/Unbread/Maps/DeathTesting.umap
  Content/Unbread/Maps/DynamicCameraTest01.umap
  Content/Unbread/Maps/HazardsTest01.umap
  Content/Unbread/Maps/Level2Test1.umap
  Content/Unbread/Maps/ModelTestLevel.umap
  Content/Unbread/Maps/ObjectiveMaterial.uasset
  Content/Unbread/Maps/ObjectiveMaterial2.uasset
  Content/Unbread/Maps/PuzzleMechanicTesting.umap
  Content/Unbread/Maps/RangedAI.umap
  Content/Unbread/Maps/Testing_Maps/AudioTest.umap
  Content/Unbread/Maps/Testing_Maps/BlockoutLevelTest.umap
  Content/Unbread/Maps/Testing_Maps/CharacterTestMaps/CharacterTest02.umap
  Content/Unbread/Maps/Testing_Maps/HazardsTest01.umap
  Content/Unbread/Maps/Testing_Maps/RangedAI.umap
  Source/unbread/Private/SRangedAICharacter.cpp
Labels: enhancement

#93 Win lose condition
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Environment/BP_WinVolume.uasset
  Content/Unbread/Maps/Testing_Maps/AudioTest.umap
  Source/unbread/Private/SRespawnGameMode.cpp
  Source/unbread/Public/SRespawnGameMode.h
Labels: enhancement, enhancement-ui, Top Priority

#99 Enemy ai
  Content/Unbread/Core/AI/Melee/AIState.uasset
  Content/Unbread/Core/AI/Melee/BB_MeleeAI.uasset
  Content/Unbread/Core/AI/Melee/BP_MeleeAICharacter.uasset
  Content/Unbread/Core/AI/Melee/BP_Melee_AIController.uasset
  Content/Unbread/Core/AI/Melee/BTServices/BTService_GetDistanceToTarget.uasset
  Content/Unbread/Core/AI/Melee/BTTasks/BTTask_ChasePlayer.uasset
  Content/Unbread/Core/AI/Melee/BTTasks/BTTask_FindPlayerLocation.uasset
  Content/Unbread/Core/AI/Melee/BTTasks/BTTask_FindWanderLocation.uasset
  Content/Unbread/Core/AI/Melee/BTTasks/BTTask_FocusTarget.uasset
  Content/Unbread/Core/AI/Melee/BTTasks/BTTask_Melee.uasset
  Content/Unbread/Core/AI/Melee/BTTasks/BTTask_PatrolRandomPoint.uasset
  Content/Unbread/Core/AI/Melee/BTTasks/BTTask_SetAnchorLocation.uasset
  Content/Unbread/Core/AI/Melee/BTTasks/BTTask_SetWalk.uasset
  Content/Unbread/Core/AI/Melee/BT_MeleeAI.uasset
  Content/Unbread/Core/AI/Melee/Eqs/MoveAwayLocation.uasset
  Content/Unbread/Core/AI/Melee/Eqs/SelectTarget.uasset
  Content/Unbread/Core/AI/Melee/Eqs/Strafe.uasset
  Content/Unbread/Core/AI/Melee/MyAIManager.uasset
  Content/Unbread/Core/AI/Melee/Path/Default.uasset
  Content/Unbread/Core/AI/Melee/Path/MySPathActor.uasset
  Content/Unbread/Core/AI/Melee/Path/Patrolling.uasset
  Content/Unbread/Core/AI/Melee/UI/DetectionMeter.uasset
  Content/Unbread/Core/AI/Melee/UI/UIInterface.uasset
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Maps/Testing_Maps/Test_MeleeAi.umap
  Source/unbread/Private/BTTask_MeleeAttack.cpp
  Source/unbread/Private/SRangedAICharacter.cpp
  Source/unbread/Public/BTTask_Fire.h
  Source/unbread/Public/BTTask_MeleeAttack.h
Labels: enhancement, backend

#105 - Added some extra donut animations
  Content/Unbread/Art/Characters/Donut/Donut_Idle_Unaware.uasset
  Content/Unbread/Art/Characters/Donut/Donut_Jump_Surprised.uasset
Labels: enhancement, graphics, backend

#106 Level camera
  Content/Unbread/Core/AI/Ranged/BP_RangedAICharacter.uasset
  Content/Unbread/Core/DynamicCamera/Release/BP_CameraSplineVolume.uasset
  Content/Unbread/Core/Input/DefaultInputMappingContext.uasset
  Content/Unbread/Environment/Hazards/StoveTopTrap.uasset
  Content/Unbread/Environment/Interactables/RotatingTable.uasset
  Content/Unbread/Maps/CoreLevelTest.umap
  Content/Unbread/Maps/Gage_Testing/FindingTheFun.umap
  Source/unbread/Private/SCharacter.cpp
Labels: enhancement, critical, backend

#111 Clean character bp
  Content/Unbread/Core/AI/Ranged/BP_RangedAICharacter.uasset
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Core/Character/BP_ExplodingBody.uasset
  Content/Unbread/Core/Interactables/BP_CrumblePile.uasset
  Source/unbread/Private/SCharacter.cpp
  Source/unbread/Private/SCrumbles.cpp
  Source/unbread/Private/SExplodingBody.cpp
  Source/unbread/Public/CameraRegisterVolume.cpp
  Source/unbread/Public/CookieInterface.h
  Source/unbread/Public/SCharacter.h
  Source/unbread/Public/SCrumbles.h
  Source/unbread/Public/SExplodingBody.h
Labels: bug, backend, Player

#112 QOL Fix: Player Animations & Cupcake Stand Glitch
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Core/Input/DefaultInputMappingContext.uasset
  Source/unbread/Private/SCharacter.cpp
  Source/unbread/Public/SCharacter.h
Labels: bug, graphics, backend

#113 Menu Hotfix
  Source/unbread/Private/SNavigatableMenu.cpp
Labels: bug, critical

#114 Selected Image Padding fix.
  Content/Unbread/Core/Input/UIInputMappingContext.uasset
  Content/Unbread/Core/UI/Widgets/WBP_Main_Menu.uasset
  Source/unbread/Private/SNavigatableMenu.cpp
  Source/unbread/Public/SNavigatableMenu.h
Labels: enhancement-ui

#115 Core Level Mod Week 8 - Game Loop completed.
  Content/Unbread/Art/Materials/DamageArea.uasset
  Content/Unbread/Art/Props/SM_Dispenser_Large.uasset
  Content/Unbread/Art/Props/Trolley_Dough_Pans.uasset
  Content/Unbread/Art/Props/Trolley_Small.uasset
  Content/Unbread/Environment/Hazards/StoveTopTrap.uasset
  Content/Unbread/Maps/CoreLevelTest.umap
Labels: backend, Design

#141 Feedback link within game, and pause menu.
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Core/GameModes/RespawnGamemode.uasset
  Content/Unbread/Core/UI/Widgets/WBP_Main_Menu.uasset
  Content/Unbread/Core/UI/Widgets/WBP_PauseMenu.uasset
  Content/Unbread/Core/UI/Widgets/WBP_WinMenu.uasset
  Source/unbread/Private/SRespawnGameMode.cpp
  Source/unbread/Public/SCharacter.h
Labels: enhancement-ui, critical

#142 Sprinting fix
  Content/Unbread/Core/Character/BP_Character.uasset
  Content/Unbread/Maps/CoreLevelTest.umap
  Source/unbread/Private/SCharacter.cpp
  Source/unbread/Private/SDestructible.cpp
  Source/unbread/Private/SRanged_AIController.cpp
  Source/unbread/Private/SRespawnGameMode.cpp
  Source/unbread/Public/SCharacter.h
Labels: enhancement

#143 reverted the bp back
  Content/Unbread/Core/Character/BP_Character.uasset
Labels: bug
